# Generated by Django 5.2.7 on 2025-11-26 17:00

from django.db import migrations


class Migration(migrations.Migration):
    """
    Placeholder migration that was originally intended to fix recipe columns.
    The actual fixes were handled by model defaults and the unified Recipe model.
    """

    dependencies = [
        ("recipes", "0004_merge_0003_follow_0003_savedrecipe"),
    ]

    operations = []
