# Generated by Django 5.2.7 on 2025-12-07 19:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_comment_like_recipe_likes"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeDraftSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        help_text="The original user prompt that generated this recipe"
                    ),
                ),
                (
                    "dietary_requirements",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional dietary restrictions specified by the user",
                    ),
                ),
                (
                    "draft_payload",
                    models.JSONField(
                        default=dict,
                        help_text="Structured recipe data from AI (form_fields dict)",
                    ),
                ),
                (
                    "assistant_display",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Formatted display text for the chat interface",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("FAILED", "Failed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "published_recipe",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to the published Recipe if status is PUBLISHED",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_draft",
                        to="recipes.recipe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe Draft Suggestion",
                "verbose_name_plural": "Recipe Draft Suggestions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "thread_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional thread identifier for grouping conversations",
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_draft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="recipes.recipedraftsuggestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "ordering": ["created_at"],
            },
        ),
    ]
