# Generated by Django 5.2.7 on 2025-12-09 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_recipedraftsuggestion_chatmessage"),
        ("recipes", "0008_recipe_image_url"),
    ]

    operations = []
