# Generated by Django 5.2.7 on 2025-11-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_follow'),
        ('recipes', '0003_savedrecipe'),
    ]

    operations = [
    ]
