# Generated by Django 5.2.7 on 2025-12-02 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_comments_count_recipe_likes_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='saves_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following_count',
        ),
    ]
